# Generated by Django 3.0.5 on 2020-04-27 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True)),
                ('duration', models.IntegerField()),
                ('cover', models.TextField(blank=True)),
                ('trailer_url', models.URLField(blank=True)),
                ('genres', models.ManyToManyField(related_name='movies', to='backend.Genre')),
            ],
        ),
    ]
