# Generated by Django 3.0.5 on 2020-04-27 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20200427_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personmovie',
            name='cast',
        ),
    ]
