# Generated by Django 3.0.5 on 2020-04-27 13:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_remove_personmovie_cast'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='castcategory',
            name='category',
        ),
        migrations.AddField(
            model_name='castcategory',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='cast',
            field=models.ManyToManyField(related_name='castcategory', through='backend.PersonMovie', to='backend.CastCategory'),
        ),
        migrations.AddField(
            model_name='personmovie',
            name='cast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.CastCategory'),
            preserve_default=False,
        ),
    ]
